### PR TITLE
Update to run as non-root.

### PR DESCRIPTION
**Pull request by j4c3**

### CODE REVIEW

**Comment by mtoensing** [comment]
I'll test this on the beta branch. Thanks https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/tree/beta

**Comment by j4c3** [comment]
Cool.  Hopefully it doesn't mess with anything else in there for you.  You'd mentioned putting the user in the Dockerfile, but I think to make it portable, it has to be pushed back to where users can define environmental variables to pass the ids.

**Comment by mtoensing** [comment]
Screen Shot 2021-04-16 at 21 11 15

So this changes the ownership to 9001:9001 of every file on the local storage, correct? Why is this better? I think this is because of this, isn't it: https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/pull/23/commits/5425142fb70f973ddd026f3b370519988946beef#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R60

 Can you please explain to me why this is a good idea?

**Comment by j4c3** [comment]
If you've run it without the PUID/PGID variables, it sets them to that as a default, so as to not give them permissions with some user/group that may already exist on the host system.

**Comment by mtoensing** [comment]
Thank you!

**Pull request merged**
