### PR TITLE
Switch to temurin

### PR DESCRIPTION
**Pull request by automate-this**
Switched base images to eclipse-temurin:17-jre (ubuntu jammy) and rewrote all scripts from alpine commands to ubuntu.
Build tested on arm64 and amd64. Ran perfectly fine on arm64.

### CODE REVIEW

**Comment by mtoensing** [comment]
Hi, 
thank you! I have a few questions though: 

Why is 

`RUN java -Dpaperclip.patchonly=true -jar /opt/minecraft/paperclip.jar; exit 0 `

not nesesarry anymore and what is meant by "full download"? 

And I really would like to keep the following notice to find the build number in the log: 

```
echo -----------------
echo $Version#$Build
echo -----------------
```

**Comment by automate-this** [comment]
Done. We are downloading the already built papermc jar file that will pull the corresponding minecraft version on start.
So I think that should suffice.
Let me say that I have learned soooo much in the last few days about docker and working with github. Thanks a lot!

**Comment by automate-this** [comment]
The way I understand it, you built the full paper server including the original minecraft inside the build container, passing it to the runtime. I dont think shipping the game with the container is a good idea.

**Comment by mtoensing** [comment]
I pushed your changes to the branch beta and image with the tag "beta" on docker hub.

I get a 

su-exec: java: No such file or directory 

on my synology AMD64 NAS. Master still works.

**Comment by automate-this** [comment]
Removed su-exec and use gosu now. Built and ran on AMD64. Please check again

**Comment by mtoensing** [comment]
nope: 
error: exec: "java": executable file not found in $PATH

**Comment by mtoensing** [comment]
Well, latest builds on github and runs on synology docker. Beta (your branch) does not. =/ There must be problem somewhere. 

and another thing I just realized. Now that you download the jar file and build it on the build stage every time the container starts for the first rime it seems to download the patched jar: 

```
First start of the docker container, start initialization process.
Starting with 9001:9001 (UID:GID)
Adding group `dockergroup' (GID 9001) ...
Done.
Adding user `dockeruser' ...
Adding new user `dockeruser' (9001) with group `dockergroup' ...
Creating home directory `/home/dockeruser' ...
Copying files from `/etc/skel' ...
changed ownership of '/opt/minecraft/paperspigot.jar' from root:root to 9001:9001
changed ownership of '/opt/minecraft/docker-entrypoint.sh' from root:root to 9001:9001
changed ownership of '/opt/minecraft' from root:root to 9001:9001
mode of '/opt/minecraft' changed from 0755 (rwxr-xr-x) to 0775 (rwxrwxr-x)
mode of '/opt/minecraft/paperspigot.jar' changed from 0644 (rw-r--r--) to 0774 (rwxrwxr--)
mode of '/opt/minecraft/docker-entrypoint.sh' changed from 0755 (rwxr-xr-x) to 0775 (rwxrwxr-x)
changed ownership of '/data' from root:root to 9001:9001
**Downloading mojang_1.19.jar**
Applying patches
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.3+7) Host: Linux 5.10.76-linuxkit (amd64)
Loading libraries, please wait...
```

Downloading the patching the jar has the benefit, that the container starts right away. Or was that your intention?

**Comment by mtoensing** [comment]
My local attempt to start the container resulted in "Loading libraries, please wait..." for 5 minutes and nothing happens. =/

**Comment by automate-this** [comment]
Correct. The jar gets redownloaded everytime the container gets destroyed/rebuilt. Yes this makes the first startup a few seconds longer, but I don't think distributing the original minecraft code with your container is something you should do? I may be wrong here, but this is exactly why paper downloads the original jar on start and patches it.

Regarding the problem on synology. Could you run the container with "-it --entrypoint sh marctv/minecraft-papermc-server".
This overrides the entrypoint and opens a shell. There you could check if java is installed and executable, java is in $PATH, or try start the server manually.

**Comment by automate-this** [comment]
I tried again with the images on dockerhub. Both on linux/AMD64 and linux/ARM64.
```
docker pull marctv/minecraft-papermc-server:beta
docker run -d --name minecraft -p 25565:25565 -v /srv/docker/test/data:/data -i marctv/minecraft-papermc-server:beta

```
Both run fine.

**Comment by mtoensing** [comment]
I have started from scratch and cleared all caches. It works now. Fixes #55

**Comment by mtoensing** [comment]
See #57 =(:::

**Pull request merged**
