### PR TITLE
Automate this patch 1

### PR DESCRIPTION
**Pull request by automate-this**
Welp. My first github contribution. Took a while.

### CODE REVIEW

**Comment by mtoensing** [comment]
Great. Can we please set TARGETARCH for amd64 by default so that existing build processes won't break?

**Comment by automate-this** [comment]
I think I dont understand correctly. I changed your build processes so both amd64 and arm64 are built via github actions.
TARGETARCH is a predefined docker variable. If you run `docker buildx build --platform linux/amd64` only TARGETARCH amd64 is used.

**Comment by automate-this** [comment]
Yes you can push to docker hub directly via github actions.
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by mtoensing** [comment]
Okay, wow. I did not know that. That changes a lot! Thanks. I will look into that

**Comment by mtoensing** [comment]
I learned a lot. Could you please pull the most recent version of my dockerimage.yml and use this https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md This results in something like that: 

```
with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
```

That way you get credit via the commit if this is okay for you. The alternative would be that I just change the code but would like to give you credit. I will remove the "beta" tag after i tested it in my yml in master.

**Comment by mtoensing** [comment]
I think it worked https://hub.docker.com/layers/minecraft-papermc-server/marctv/minecraft-papermc-server/beta/images/sha256-abb7b984468460b4773d682dead8e06b97f2e47bfba0a28be2787f9ad3eb8541?context=explore

**Pull request merged**
