### PR TITLE
Java 16

### PR DESCRIPTION
**Pull request by j4c3**
It looks like 1.17 will require Java 16, so I made some changes to the container to get that support rolling now. 

The plugins I use have finally updated to support it, so on Java 16 everything started up, and I was able to access the server (through Geyser/Floodgate). 

I haven't tested much beyond that, yet.

### CODE REVIEW

**Comment by mtoensing** [comment]
Merged into beta branch for testing.

**Comment by mtoensing** [comment]
@j4c3 Thank you. But why not use openjdk:16 instead of alpine? Does it have an advantage? Because with openjdk I just could change the number and leave all paths as it. What do you think?

**Comment by j4c3** [comment]
I tried that!  Apparently they had a change in philosophy between 11 and 16, and the base image is just for running Java apps, and doesn't come with utils you'd expect.  I'm not as familiar with Alpine either, but that build had busybox and a package manager. 
 The Alpine build is smaller than some of the others, but I think you'd have to select 16-something.

**Comment by mtoensing** [comment]
Okay, Great! I leave it that way. Seems to run fine for me.

**Pull request merged**
